### ISSUE TITLE
Closed loop demo for ROS2

### ISSUE THREAD

**Issue by shawnlin427** [2b-t/ros_closed_loops#3]
Hi, I have create a ros2 foxy version of four-bar linkage example, links here: https://github.com/0smile/closed_loop/tree/foxy

Thanks to @2b-t for your creative work!

**Comment by 2b-t** [comment]
Hey @0smile thanks for your contribution.
I will have a look the following days (most likely on the weekend) and merge it.

**Comment by shawnlin427** [comment]
>

**Comment by shawnlin427** [comment]
> Hey @0smile thanks for your contribution. I will have a look the following days (most likely on the weekend) and merge it.

Thanks! And you may want to checkout the ros2_control branch, which uses gazebo_ros2_control to synchronize the robot in both ros2 and gazebo.
